[package]
name = "darling-api"
version = "0.1.3"
edition = "2021"
authors = ["Violet Iapalucci"]
license = "MIT"
description = "Library API for darling"
readme = "README.md"

[dependencies]
anyhow = "1.0.81"
